import { NgModule } from '@angular/core';
import {
  LucideLayoutDashboard,
  LucideMenu,
  LucideX,
  LucideChevronLeft,
  LucideChevronRight,
  LucideSettings,
  LucideTrendingUp,
  LucideTrendingDown,
  LucideShoppingCart,
  LucideClock,
  LucideCircleDollarSign,
  LucidePlus,
  LucidePencil,
  LucideTrash2,
  LucideAlertTriangle,
  LucideInfo,
  LucideCheckCircle,
  LucideEye,
  LucideEyeOff,
  LucideDownload,
  LucideUpload,
  LucideShield,
  LucideBarChart2,
  LucideRefreshCw,
  LucideLandmark,
  LucideScale,
  LucideHelpCircle,
  LucideXCircle,
  LucideBell,
  LucideCreditCard,
  LucideList,
} from '@lucide/angular';

export const LUCIDE_ICONS = [
  LucideLayoutDashboard,
  LucideMenu,
  LucideX,
  LucideChevronLeft,
  LucideChevronRight,
  LucideSettings,
  LucideTrendingUp,
  LucideTrendingDown,
  LucideShoppingCart,
  LucideClock,
  LucideCircleDollarSign,
  LucidePlus,
  LucidePencil,
  LucideTrash2,
  LucideAlertTriangle,
  LucideInfo,
  LucideCheckCircle,
  LucideEye,
  LucideEyeOff,
  LucideDownload,
  LucideUpload,
  LucideShield,
  LucideBarChart2,
  LucideRefreshCw,
  LucideLandmark,
  LucideScale,
  LucideHelpCircle,
  LucideXCircle,
  LucideBell,
  LucideCreditCard,
  LucideList,
] as const;


